### ISSUE TITLE
Portfolio Peer Review

### ISSUE THREAD

**Issue by ksheedy** [zhaojanelle/portfolio-site#1]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | All pages exist and are well done with complete imagery |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | Unique and recognizable as you, with engaging, personable content & design |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | High quality portfolio images — and lots of them |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

Pages & Images - 2.5 - lots and lots of content, only one case study missing content
Personality & design - 3 - lots of great small touches that create visual interest and make me want to explore
Image Quality - 3 - lots and lots of great content
Accessibility - 0 - but I know you'll get there!
Text Content - 3 
Responsiveness - 3
Code quality - 3

-Site is very well organized with lots and lots of content
-it is a little bit hard to read the links in the footer when there is text behind
-consider having a way to navigate between case study pages at smaller screen sizes, like a next/previous

**Comment by zhaojanelle** [comment]
fixed text in footer
added "top" button to go to nav
