### ISSUE TITLE
Peer Critique - AR

### ISSUE THREAD

**Issue by arobillard** [zhaojanelle/portfolio-site#2]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & images** | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | **All pages exist and are well done with complete imagery** |
| **Personality & design** | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | **Unique and recognizable as you, with engaging, personable content & design** |
| **Image quality** | Only placeholder images | Some portfolio piece images | Lots of images but low quality | **High quality portfolio images — and lots of them** |
| **Accessibility** | **No considerations** | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Responsiveness** | Not responsive | Works on some screens | **Responsive but with lots of awkwardness** | Looks great on all screen sizes |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | **Decent indentation, just a couple validation errors, decent semantics** | Well indented, fully valid, good semantics |

**About Page**
- add a hyperlink to your email /w mailto: (also on homepage)
- Maybe increase the type hierarchy for the "Education" & "Work" titles

**Accessibility**
- I would recommend adding embed containers to your images. Your layout breaks when the images do not load in
- the red/black colour contrast does not come through well for visual impairments and colourblindness

**General**
- "Hire Me" button link is broken
- the "Hire Me" button feels too large and intrusive at mobile/small screen sizes
- file path is inconsistent. Your case studies are under "work" in your navigation, but the file path in the url is "projects"

**Comment by zhaojanelle** [comment]
Added the hyperlink
reworked type hierarchy
no more red/black
hire me button linked
removed hire me on mobile
fixed file path
