### ISSUE TITLE
Portfolio Peer Review

### ISSUE THREAD

**Issue by hollixholton** [zhaojanelle/portfolio-site#3]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| *Pages & images* | Barely started | Missing lots of pages & images | Has most of the pages, some placeholder images | All pages exist and are well done with complete imagery |
| *Personality & design* | Bland, boring, just another graphic designer | Fairly generic, visual design could be pushed more | Quality layouts and unique, personable content & design | Unique and recognizable as you, with engaging, personable content & design |
| *Image quality* | Only placeholder images | Some portfolio piece images | Lots of images but low quality | High quality portfolio images — and lots of them |
| *Accessibility* | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| *Text content* | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
| *Responsiveness* | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
| *Code quality* | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

Pages and Images - 3
Personality and Design - 3
Image Quality - 3
Accessibility - 2
Text Content - 3
Responsiveness - 2
Code Quality -3

This is actually super cute and i'm not even just saying that. (The hire me button is the cutest)
The only issue i ran into is when i opened the website for the first time, the nav was covering stuff? I think that might have been a glitch because once i adjusted the page size it went back to normal!

**Comment by zhaojanelle** [comment]
Fixed the nav issue
